### ISSUE TITLE
Test `kwasow/malformed` is malformed

### ISSUE THREAD

**Issue by top-sekret** [Kwasow/JNP_testy#12]
Leading zeroes are correct input according to the expected output/error provided, which is wrong.

**Comment by Kwasow** [comment]
Indeed, leading zeros are allowed but this line is incorrect due to a different reason. The `malformed` test is a modified official test. The number 7 is incorrect because it has not received any votes in the previous vote and therefore has been removed. Leading zeros are not the issue here.

Is that clear? I've had a beer or two, sorry.
